/**
 * Companion (xTrace + Claude) API schemas — docs/xtrace-hackathon-tasks.md XH-T1.
 * Consumed by the banter route/panel (XH-T6), the callout-draft route/button (XH-T7),
 * and the season-recap job/panel (XH-T8). Only what a task consumes is defined here.
 */
import { z } from 'zod';
import { COMPANION_BANTER_MAX_LINES, COMPANION_DRAFT_MAX } from '../config.js';
import { zProfileId } from '../ids.js';
import { zTimestamp } from './common.js';

/**
 * `GET /api/v1/pairings/:id/banter` response. `banter: null` means the feature is degraded
 * or unconfigured — always a 200; the client island renders nothing (XH-T6 fail-open rule).
 * `generated_at` is the stored artifact row's `createdAt`, never `now()`.
 */
export const getBanterResponseSchema = z.object({
  banter: z
    .object({
      lines: z.array(z.string().min(1).max(280)).min(1).max(COMPANION_BANTER_MAX_LINES),
      generated_at: zTimestamp,
    })
    .nullable(),
});
export type GetBanterResponse = z.infer<typeof getBanterResponseSchema>;

/** `POST /api/v1/callouts/draft` request body (XH-T7). */
export const draftCalloutBodySchema = z
  .object({
    target_profile_id: zProfileId,
  })
  .strict();
export type DraftCalloutBody = z.infer<typeof draftCalloutBodySchema>;

/** `POST /api/v1/callouts/draft` response (XH-T7). Degraded generation is a 503
 * `COMPANION_UNAVAILABLE` error envelope, never `drafts: []`. */
export const draftCalloutResponseSchema = z.object({
  drafts: z.array(z.string().min(1).max(280)).min(1).max(COMPANION_DRAFT_MAX),
});
export type DraftCalloutResponse = z.infer<typeof draftCalloutResponseSchema>;

/** The recap content generated by XH-T3's `seasonRecap` and stored in
 * `companion_artifacts.content.recap` (XH-T8). No `getRecapResponseSchema` — the `/you`
 * panel is server-rendered straight from the DB row, no GET recap route exists in any task,
 * so a response schema would have no consumer. */
export const seasonRecapContentSchema = z.object({
  title: z.string().min(1).max(120),
  paragraphs: z.array(z.string().min(1).max(600)).min(1).max(4),
});
export type SeasonRecapContent = z.infer<typeof seasonRecapContentSchema>;
