/**
 * WS19-T2 E2E: the Sweat room (`/sweat`) + the settle-on-resolution question-page states
 * (journeys-plan §5, D-J3).
 *
 * NOTE: first run is CI. This repo's sandbox has no browser/CDN, so the Playwright suite and any
 * `toHaveScreenshot` baselines are generated by CI, not locally (see this task's PR notes). The
 * assertions here are content-based (labels, ordering, empty state) — no new screenshot baseline
 * is introduced by this file; the only new baseline this task adds is `sweatrow` in
 * `dev-ui-visual.spec.ts`.
 *
 * Seeds real rows directly into Postgres (`DATABASE_URL`, migrated by the `e2e` CI job) since
 * `/sweat` reads the DB directly for SSR (`lib/sweat-feed.ts`), exactly like
 * `question-page.spec.ts`/`obituary-wake.spec.ts`. The viewer is a REAL ghost profile with a real
 * `rcpt_gid` cookie (not a mocked identity), so the page's own `resolveViewerIdentity` resolves it
 * the same way a route handler would. Every unique-ish default is forced to a fresh UUID per call
 * to stay collision-free under `fullyParallel: true` + CI retries (see `question-page.spec.ts`'s
 * `seedQuestion` header for the shared hazard).
 */
import { randomUUID } from 'node:crypto';
import { expect, test } from '@playwright/test';
import { connect, markets, picks, profiles, questions, type Db } from '@receipts/db';
import { buildMarket, buildPick, buildProfile, buildQuestion } from '@receipts/db/testing';
import {
  buildGhostCookieValue,
  generateGhostSecret,
  GHOST_COOKIE_NAME,
  hashGhostSecret,
} from '../lib/ghost-cookie';
import type pg from 'pg';

const DATABASE_URL =
  process.env.DATABASE_URL ?? 'postgres://receipts:receipts@localhost:5432/receipts';

let pool: pg.Pool;
let db: Db;

test.beforeAll(() => {
  ({ pool, db } = connect({ connectionString: DATABASE_URL }));
});

test.afterAll(async () => {
  await pool.end();
});

async function seedGhost(): Promise<{ profileId: string; secret: string }> {
  const unique = randomUUID();
  const secret = generateGhostSecret();
  const profile = buildProfile({
    handle: `Sweat ${unique}`,
    slug: `sweat-${unique}`,
    ghostSecretHash: hashGhostSecret(secret),
  });
  await db.insert(profiles).values(profile);
  return { profileId: profile.id as string, secret };
}

/** Seeds a market + question + a pending pick for `profileId`, with the market closing at
 * `closeTime` and the venue currently at `yesPriceNow`. Returns the seeded question. */
async function seedPendingPosition(
  profileId: string,
  opts: {
    closeTime: Date;
    headline: string;
    side?: 'yes' | 'no';
    entry?: number;
    yesPriceNow?: number;
  },
) {
  const unique = randomUUID();
  const market = buildMarket({
    venueMarketId: `KX-SWEAT-${unique}`,
    status: 'open',
    closeTime: opts.closeTime,
    yesPrice: opts.yesPriceNow ?? 0.63,
  });
  await db.insert(markets).values(market);
  const question = buildQuestion(market.id as string, {
    slug: `sweat-${unique}`,
    questionDate: null,
    status: 'locked',
    headline: opts.headline,
  });
  await db.insert(questions).values(question);
  await db.insert(picks).values(
    buildPick(question.id as string, profileId, {
      side: opts.side ?? 'yes',
      yesPriceAtEntry: opts.entry ?? 0.6,
      result: 'pending',
    }),
  );
  return question;
}

test.describe('WS19-T2 /sweat — open positions by settle-time', () => {
  test('a ghost with pending picks sees them soonest-first with settle-when labels', async ({
    page,
  }) => {
    const { profileId, secret } = await seedGhost();
    const now = Date.now();

    // Deliberately seeded out of settle order to prove the page sorts them.
    await seedPendingPosition(profileId, {
      closeTime: new Date(now + 90 * 24 * 3600_000), // far future → ~MON YYYY
      headline: 'Far settle headliner',
      yesPriceNow: 0.5,
      entry: 0.6,
    });
    await seedPendingPosition(profileId, {
      closeTime: new Date(now + 60 * 60_000), // < 2h → LIVE
      headline: 'Live settle headliner',
      yesPriceNow: 0.7,
      entry: 0.6,
    });
    await seedPendingPosition(profileId, {
      closeTime: new Date(now + 3 * 24 * 3600_000), // < 7d → weekday
      headline: 'Weekday settle headliner',
      yesPriceNow: 0.6,
      entry: 0.6,
    });

    await page.context().addCookies([
      {
        name: GHOST_COOKIE_NAME,
        value: buildGhostCookieValue(profileId, secret),
        domain: 'localhost',
        path: '/',
        httpOnly: true,
        secure: true,
        sameSite: 'Lax',
      },
    ]);

    await page.goto('/sweat');

    const rows = page.getByTestId('sweat-row');
    await expect(rows).toHaveCount(3);

    // Soonest-first: LIVE row is first, the far ~MON YYYY row is last.
    await expect(rows.first()).toContainText('Live settle headliner');
    await expect(rows.first().getByTestId('sweat-settle-label')).toHaveText('LIVE');
    await expect(rows.last()).toContainText('Far settle headliner');
    await expect(rows.last().getByTestId('sweat-settle-label')).toContainText('~');
  });

  test('an anonymous visitor (no ghost, no session) sees the empty state linking home', async ({
    page,
  }) => {
    await page.context().clearCookies();
    await page.goto('/sweat');
    await expect(page.getByTestId('sweat-empty')).toBeVisible();
    await expect(page.getByTestId('sweat-empty-cta')).toHaveAttribute('href', '/');
  });
});

test.describe('WS19-T2 question page — settle-on-resolution presentation', () => {
  test('a locked question shows "settles when it settles", not a reveal countdown', async ({
    page,
  }) => {
    const unique = randomUUID();
    const market = buildMarket({ venueMarketId: `KX-SWEAT-LOCK-${unique}`, status: 'closed' });
    await db.insert(markets).values(market);
    const question = buildQuestion(market.id as string, {
      slug: `sweat-locked-${unique}`,
      questionDate: null,
      status: 'locked',
      headline: 'Does the locked fixture settle later?',
      crowdYesAtLock: 7,
      crowdNoAtLock: 3,
    });
    await db.insert(questions).values(question);

    await page.goto(`/q/${question.slug}`);
    await expect(page.getByTestId('question-locked')).toBeVisible();
    await expect(page.getByTestId('settle-when')).toContainText('SETTLES WHEN IT SETTLES');
  });

  test('a settled (revealed) question stamps the real settle time', async ({ page }) => {
    const unique = randomUUID();
    const revealedAt = new Date();
    const market = buildMarket({
      venueMarketId: `KX-SWEAT-DONE-${unique}`,
      status: 'resolved',
      outcome: 'yes',
    });
    await db.insert(markets).values(market);
    const question = buildQuestion(market.id as string, {
      slug: `sweat-settled-${unique}`,
      questionDate: null,
      status: 'revealed',
      outcome: 'yes',
      crowdYesAtLock: 7,
      crowdNoAtLock: 3,
      settledAt: revealedAt,
      revealedAt,
    });
    await db.insert(questions).values(question);

    await page.goto(`/q/${question.slug}`);
    await expect(page.getByTestId('question-revealed')).toBeVisible();
    await expect(page.getByTestId('settled-at')).toContainText('SETTLED');
  });
});
