/**
 * `companion:season-recap` (XH-T8, docs/xtrace-hackathon-tasks.md): one narrative recap per
 * claimed profile per nemesis season, generated by this batch job — NEVER in-request (an LLM
 * call + xTrace search per profile is far too slow/costly to gate a page render on) — and
 * rendered server-side on `/you` from the stored artifact.
 *
 * Queue-only (no cron): a nemesis season runs 12 weeks, so there's no useful clock cadence to
 * schedule against yet; trigger manually via `run-season-recap.mjs` (ops, and the XH-T9 demo
 * runbook) or wire a cron later once there's a real cadence to pick.
 *
 * Sequential per-profile loop — no concurrency (a season of hackathon scale is tens of profiles;
 * each iteration is bounded by one LLM attempt + one xTrace search). A worst-case run can still
 * exceed pg-boss's default job expiration; that's safe, not a bug — a re-delivered run skips
 * already-stored recaps (step 1 below) and `insertArtifactIdempotent` dedupes any concurrent
 * store from an overlapping re-delivery.
 */
import {
  COMPANION_MODEL,
  COMPANION_PROMPT_VERSION,
  etDateString,
  isFlagEnabled,
  now,
} from '@receipts/core';
import {
  getArtifactByCacheKey,
  getProfileById,
  getSeasonById,
  insertArtifactIdempotent,
  latestEndedNemesisSeason,
  listClaimedProfileIdsInSeason,
  listCompletedSeasonPairingsForProfile,
  listSentCalloutsWithPairingOutcome,
  recapCacheKey,
  type CompanionArtifactContent,
  type Db,
  type SeasonPairingForStats,
  type SentCalloutForStats,
} from '@receipts/db';
import type { SeasonRow } from '@receipts/db';
import {
  generatorFromEnv,
  xtraceClientFromEnv,
  type Generator,
  type RecapContext,
  type XtraceClient,
} from '@receipts/companion';
import type { JobContext } from '../context.js';
import type { JobHandler } from '../heartbeat.js';
import { logger } from '../logger.js';
import { ownNarrationLine } from '../lib/verdict-narration.js';

export interface CompanionSeasonRecapReport {
  seasonId: string | null;
  generated: number;
  skippedExisting: number;
  skippedFailed: number;
}

function zeroedReport(): CompanionSeasonRecapReport {
  return { seasonId: null, generated: 0, skippedExisting: 0, skippedFailed: 0 };
}

/** Given id → that season as-is, no `endsOn` check (it may still be running). Omitted → the
 * latest-ended `nemesis` season as of `today` (ET calendar date). */
async function resolveSeason(
  db: Db,
  seasonId: string | undefined,
  today: string,
): Promise<SeasonRow | null> {
  if (seasonId) return getSeasonById(db, seasonId);
  return latestEndedNemesisSeason(db, today);
}

interface SeasonPairingStats {
  pairings: number;
  wins: number;
  losses: number;
  draws: number;
  bestStreak: number;
  verdictLines: string[];
}

/** Folds the profile's ordered (oldest-first) completed-pairing list once: win/loss/draw
 * bucketing, the longest consecutive-WIN streak (a draw or a loss both break the run), and the
 * chronological verdict lines — all three pinned to this exact list/order (XH-T8 spec). */
function computeSeasonPairingStats(
  pairings: SeasonPairingForStats[],
  profileId: string,
): SeasonPairingStats {
  let wins = 0;
  let losses = 0;
  let draws = 0;
  let bestStreak = 0;
  let currentStreak = 0;
  const verdictLines: string[] = [];

  for (const p of pairings) {
    if (p.winnerProfileId === null) {
      draws += 1;
      currentStreak = 0;
    } else if (p.winnerProfileId === profileId) {
      wins += 1;
      currentStreak += 1;
      bestStreak = Math.max(bestStreak, currentStreak);
    } else {
      losses += 1;
      currentStreak = 0;
    }
    const line = ownNarrationLine(p.verdict, profileId);
    if (line) verdictLines.push(line);
  }

  return { pairings: pairings.length, wins, losses, draws, bestStreak, verdictLines };
}

/** Filters `profileId`'s sent callouts to the season's ET-day window (`etDateString` string
 * comparison — see `listSentCalloutsWithPairingOutcome`'s header for why NOT a SQL date cast),
 * then counts sent vs. won (won = the callout's pairing is `completed` with this profile as
 * winner). */
function computeSeasonCalloutStats(
  sentCallouts: SentCalloutForStats[],
  profileId: string,
  season: SeasonRow,
): { calloutsSent: number; calloutsWon: number } {
  const inSeason = sentCallouts.filter((c) => {
    const day = etDateString(c.createdAt);
    return day >= season.startsOn && day <= season.endsOn;
  });
  const calloutsWon = inSeason.filter(
    (c) => c.pairingStatus === 'completed' && c.pairingWinnerProfileId === profileId,
  ).length;
  return { calloutsSent: inSeason.length, calloutsWon };
}

async function recapOneProfile(
  db: Db,
  xtrace: XtraceClient,
  generator: Generator,
  season: SeasonRow,
  profileId: string,
): Promise<'generated' | 'failed'> {
  const [pairings, sentCallouts, profile] = await Promise.all([
    listCompletedSeasonPairingsForProfile(db, season.id, profileId),
    listSentCalloutsWithPairingOutcome(db, profileId),
    getProfileById(db, profileId),
  ]);
  const handle = profile?.handle ?? profileId;

  const {
    pairings: pairingsCount,
    wins,
    losses,
    draws,
    bestStreak,
    verdictLines,
  } = computeSeasonPairingStats(pairings, profileId);
  const { calloutsSent, calloutsWon } = computeSeasonCalloutStats(sentCallouts, profileId, season);

  const memory = await xtrace.search({
    userId: profileId,
    query: 'season rivalry highlights grudges',
    include: ['episode', 'fact'],
  });

  const ctx: RecapContext = {
    handle,
    seasonName: season.name,
    stats: {
      pairings: pairingsCount,
      wins,
      losses,
      draws,
      bestStreak,
      calloutsSent,
      calloutsWon,
    },
    verdictLines,
    memory: memory.map((m) => m.text),
  };

  const recap = await generator.seasonRecap(ctx);
  if (!recap) return 'failed';

  const content: CompanionArtifactContent = {
    recap,
    model: COMPANION_MODEL,
    promptVersion: COMPANION_PROMPT_VERSION,
  };
  await insertArtifactIdempotent(db, {
    kind: 'season_recap',
    cacheKey: recapCacheKey(season.id, profileId),
    profileId,
    pairingId: null,
    seasonId: season.id,
    content,
  });
  return 'generated';
}

export async function runSeasonRecap(
  ctx: JobContext,
  xtrace: XtraceClient,
  generator: Generator,
  seasonId?: string,
  at: Date = now(),
): Promise<CompanionSeasonRecapReport> {
  const today = etDateString(at);
  const season = await resolveSeason(ctx.db, seasonId, today);
  if (!season) {
    logger.warn({ seasonId }, 'companion:season-recap — no season resolved, nothing to do');
    return zeroedReport();
  }

  const profileIds = await listClaimedProfileIdsInSeason(ctx.db, season.id);
  const report: CompanionSeasonRecapReport = {
    seasonId: season.id,
    generated: 0,
    skippedExisting: 0,
    skippedFailed: 0,
  };

  for (const profileId of profileIds) {
    const cacheKey = recapCacheKey(season.id, profileId);
    const existing = await getArtifactByCacheKey(ctx.db, cacheKey);
    if (existing) {
      report.skippedExisting += 1;
      continue;
    }

    const outcome = await recapOneProfile(ctx.db, xtrace, generator, season, profileId);
    if (outcome === 'generated') report.generated += 1;
    else report.skippedFailed += 1;
  }

  return report;
}

export const companionSeasonRecapHandler: JobHandler = async (ctx, data) => {
  if (!isFlagEnabled('season_wrapped')) {
    logger.debug('companion:season-recap skipped — season_wrapped flag disabled');
    return;
  }
  const xtrace = xtraceClientFromEnv();
  const generator = generatorFromEnv();
  if (!xtrace || !generator) {
    logger.debug('companion:season-recap skipped — xTrace/generator unconfigured');
    return;
  }

  const parsed = data as { seasonId?: string } | undefined;
  const report = await runSeasonRecap(ctx, xtrace, generator, parsed?.seasonId);
  logger.info({ report }, 'companion:season-recap complete');
};
